export { default as Home } from './Home/Home'
export { default as About } from './About/About'
export { default as Blog } from './Blog/Blog'
export { default as Portfolio } from './Portfolio/Portfolio'
export { default as PortfolioItem } from './Portfolio/PortfolioItem'
export { default as Contact } from './Contact/Contact'
export { default as NotFound } from './NotFound/NotFound'
